ci: debug printouts for running action in docker container
Refs: #32

diff --git a/.github/workflows/_generate-helm-release-manifest.yml b/.github/workflows/_generate-helm-release-manifest.yml
--- a/.github/workflows/_generate-helm-release-manifest.yml
+++ b/.github/workflows/_generate-helm-release-manifest.yml
@@ -9,6 +9,11 @@ jobs:
     runs-on: ubuntu-latest
     container: ghcr.io/fluxcd/flux-cli:v0.30.2
     steps:
+      - uses: actions/checkout@v2
       - name: Create manifest
         run: |
+          echo "Content of /github/
+          ls -la  /github/ 2>/dev/null || echo "/github/ Not found"
+          echo "Content of /github/workspace/
+          ls -la  /github/ 2>/dev/null || echo "/github/workspace/ Not found"
           flux create hr pipeline-lab --source=HelmRepository/visegue-public --chart=pipeline-lab --values=/github/workspace/helm/values/values.yaml --values=/github/workspace/helm/values/values-staging.yaml --interval=10m --namespace=demo-staging --export
